const $=s=>document.querySelector(s),fmt=n=>'₹'+n.toLocaleString('en-IN');
const ld=(k,d)=>{try{const v=JSON.parse(localStorage.getItem(k));return v??d}catch(e){return d}};
const sv=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}};
const ar=(k,d)=>{const v=ld(k,d);return Array.isArray(v)?v:d};
/* ---------- data ---------- */
const R=[['Apple','iPhone 15 Pro','Smartphones','phone',119900,139900,4.8,2140,'#8a8f9c'],['Samsung','Galaxy S24 Ultra','Smartphones','phone',129999,144999,4.7,1820,'#3a3f4d'],['Google','Pixel 8 Pro','Smartphones','phone',99999,106999,4.6,960,'#5d7a9c'],['OnePlus','12 5G','Smartphones','phone',64999,69999,4.5,1330,'#2d4a3e'],
['Apple','MacBook Air M2','Laptops','laptop',99990,119900,4.9,2310,'#b9bcc6'],['ASUS','ROG Zephyrus G14','Laptops','laptop',124990,149990,4.7,980,'#3b3f55'],['Dell','XPS 13 Plus','Laptops','laptop',109990,129990,4.5,740,'#9aa3b5'],['Lenovo','ThinkPad X1 Carbon','Laptops','laptop',139990,159990,4.6,520,'#23262f'],
['Sony','WH-1000XM5','Audio','head',29990,34990,4.8,1412,'#1b1f2e'],['Sennheiser','Momentum 4','Audio','head',34990,39990,4.7,610,'#3a3a3f'],['boAt','Rockerz 450','Audio','head',1999,3990,4.3,3200,'#c23b4e'],['Bose','QuietComfort Ultra','Audio','head',35900,39900,4.7,880,'#d8d4cc'],
['Apple','AirPods Pro (2nd Gen)','Audio','buds',24900,26900,4.8,2100,'#f2f3f6'],['Sony','WF-1000XM4','Audio','buds',19990,24990,4.7,1100,'#25283a'],['boAt','Airdopes 141','Audio','buds',1299,2499,4.2,2200,'#1b1f2e'],
['JBL','Charge 5','Audio','spk',14999,19999,4.6,1200,'#2a5bd7'],['Marshall','Emberton II','Audio','spk',14999,17999,4.6,760,'#17171a'],
['Amazon','Echo Dot (5th Gen)','Smart Home','hub',4499,5499,4.5,5100,'#3b4a63'],['Google','Nest Hub','Smart Home','hub',8999,10999,4.4,1400,'#d9dce3'],
['Samsung','Galaxy Watch 6','Accessories','watch',25999,32999,4.4,870,'#2b2f3d'],['Apple','Watch Series 9','Accessories','watch',45900,49900,4.8,1560,'#c9a98a'],
['Keychron','Q1 Pro Keyboard','Accessories','kb',14999,17999,4.7,640,'#444b63'],['Logitech','MX Master 3S','Accessories','mouse',9995,10995,4.8,2900,'#2c2f3a'],
['GoPro','HERO12 Black','Lifestyle','cam',31999,39999,4.6,980,'#16181f'],['Sony','ZV-E10 Vlog Camera','Lifestyle','cam',59990,69990,4.6,430,'#25262e']]
.map((r,i)=>({id:i,brand:r[0],name:r[1],cat:r[2],type:r[3],price:r[4],orig:r[5],rating:r[6],rev:r[7],color:r[8],stock:i!==10,sold:30+(i*17)%65,disc:Math.round((1-r[4]/r[5])*100)}));
const CATS=[['Smartphones','Latest devices','phone'],['Laptops','High performance','laptop'],['Audio','Immerse yourself','head'],['Smart Home','Smarter living','hub'],['Accessories','Everyday essentials','watch'],['Lifestyle','Capture life','cam']];
/* ---------- product art: shared renderer ---------- */
const shade=(h,a)=>{let n=parseInt(h.slice(1),16),r=n>>16,g=n>>8&255,b=n&255,f=a<0?0:255,p=Math.abs(a);return '#'+[r,g,b].map(v=>Math.round((f-v)*p+v).toString(16).padStart(2,'0')).join('')};
function art(t,c,u,n){const i='a'+u,L=shade(c,.45),M=shade(c,.12),D=shade(c,-.4),P=`url(#${i}b)`,W=`url(#${i}w)`,S=`url(#${i}s)`;
const defs=`<defs><linearGradient id="${i}g" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#fbfcff"/><stop offset="1" stop-color="#dce2f1"/></linearGradient><radialGradient id="${i}h" cx=".5" cy=".42" r=".55"><stop offset="0" stop-color="${shade(c,.6)}" stop-opacity=".45"/><stop offset="1" stop-color="${c}" stop-opacity="0"/></radialGradient><linearGradient id="${i}b" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="${L}"/><stop offset=".5" stop-color="${M}"/><stop offset="1" stop-color="${D}"/></linearGradient><linearGradient id="${i}s" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#2d5bff"/><stop offset=".55" stop-color="#7c3cff"/><stop offset="1" stop-color="#ff5fa2"/></linearGradient><linearGradient id="${i}w" x1="0" y1="0" x2="1" y2="0"><stop offset="0" stop-color="#fff" stop-opacity=".6"/><stop offset="1" stop-color="#fff" stop-opacity="0"/></linearGradient><filter id="${i}f" x="-30%" y="-30%" width="160%" height="160%"><feGaussianBlur stdDeviation="5"/></filter></defs>`;
const B={
phone:`<g transform="rotate(-9 70 110) translate(-22 6)"><rect x="52" y="30" width="62" height="136" rx="13" fill="${P}"/><rect x="74" y="38" width="30" height="30" rx="8" fill="${D}" stroke="${L}" stroke-width=".8"/><circle cx="82" cy="46" r="5.2" fill="#0b1020" stroke="${L}"/><circle cx="82" cy="60" r="5.2" fill="#0b1020" stroke="${L}"/><circle cx="96" cy="53" r="5.2" fill="#0b1020" stroke="${L}"/><rect x="52" y="30" width="62" height="136" rx="13" fill="${W}" opacity=".35"/></g><g transform="rotate(5 130 100)"><rect x="100" y="26" width="68" height="144" rx="15" fill="${P}"/><rect x="104" y="30" width="60" height="136" rx="11" fill="#05070f"/><rect x="106" y="32" width="56" height="132" rx="9" fill="${S}"/><path d="M106 120q28-30 56-8v52h-56z" fill="#fff" opacity=".13"/><rect x="123" y="36" width="22" height="6" rx="3" fill="#05070f"/><text x="134" y="84" text-anchor="middle" font-size="22" font-weight="700" fill="#fff" font-family="Inter,sans-serif">9:41</text><rect x="100" y="26" width="68" height="144" rx="15" fill="none" stroke="${L}" stroke-opacity=".7"/></g>`,
laptop:`<path d="M40 52a6 6 0 0 1 6-6h108a6 6 0 0 1 6 6v82H40z" fill="${P}"/><rect x="45" y="51" width="110" height="78" rx="2" fill="#05070f"/><rect x="46" y="52" width="108" height="76" fill="${S}"/><path d="M46 100q30-34 62-10t46-8v46H46z" fill="#fff" opacity=".16"/><path d="M46 112q40-20 72 0t36-6v22H46z" fill="#000" opacity=".15"/><rect x="88" y="52" width="24" height="4" rx="2" fill="#05070f"/><path d="M26 136h148l-8 12a6 6 0 0 1-5 3H39a6 6 0 0 1-5-3z" fill="${P}"/><path d="M26 136h148" stroke="${L}" stroke-width="1.5"/><rect x="84" y="137" width="32" height="3.5" rx="1.7" fill="${D}"/>`,
head:`<path d="M54 112V92a46 46 0 0 1 92 0v20" fill="none" stroke="${D}" stroke-width="13" stroke-linecap="round"/><path d="M54 112V92a46 46 0 0 1 92 0v20" fill="none" stroke="${P}" stroke-width="9" stroke-linecap="round"/><path d="M62 70a46 46 0 0 1 40-17" fill="none" stroke="#fff" stroke-opacity=".5" stroke-width="2.5" stroke-linecap="round"/><rect x="36" y="98" width="34" height="62" rx="17" fill="${D}"/><rect x="40" y="100" width="28" height="58" rx="14" fill="${P}"/><ellipse cx="66" cy="129" rx="6" ry="24" fill="${shade(c,-.6)}"/><rect x="44" y="108" width="6" height="26" rx="3" fill="#fff" opacity=".35"/><rect x="130" y="98" width="34" height="62" rx="17" fill="${D}"/><rect x="132" y="100" width="28" height="58" rx="14" fill="${P}"/><ellipse cx="134" cy="129" rx="6" ry="24" fill="${shade(c,-.6)}"/><rect x="150" y="108" width="6" height="26" rx="3" fill="#fff" opacity=".35"/>`,
buds:`<rect x="52" y="108" width="96" height="58" rx="26" fill="${P}"/><path d="M52 132h96" stroke="${D}" stroke-width="1.5"/><circle cx="100" cy="148" r="2.6" fill="#7dffb0"/><rect x="52" y="108" width="96" height="58" rx="26" fill="${W}" opacity=".4"/><g transform="rotate(-12 76 70)"><ellipse cx="76" cy="62" rx="15" ry="17" fill="${P}"/><rect x="82" y="66" width="9" height="34" rx="4.5" fill="${P}"/><circle cx="72" cy="60" r="4" fill="${D}"/></g><g transform="rotate(12 124 70)"><ellipse cx="124" cy="62" rx="15" ry="17" fill="${P}"/><rect x="109" y="66" width="9" height="34" rx="4.5" fill="${P}"/><circle cx="128" cy="60" r="4" fill="${D}"/></g>`,
watch:`<path d="M78 8h44l4 48H74z" fill="${D}"/><path d="M74 144h52l-4 48H78z" fill="${D}"/><rect x="56" y="52" width="88" height="96" rx="26" fill="${P}"/><rect x="62" y="58" width="76" height="84" rx="21" fill="#05070f"/><g fill="none" stroke-width="5" stroke-linecap="round" transform="rotate(-90 100 100)"><circle cx="100" cy="100" r="30" stroke="#ff2d55" stroke-opacity=".25"/><circle cx="100" cy="100" r="30" stroke="#ff2d55" stroke-dasharray="130 190"/><circle cx="100" cy="100" r="22" stroke="#7dff4f" stroke-opacity=".25"/><circle cx="100" cy="100" r="22" stroke="#7dff4f" stroke-dasharray="90 140"/><circle cx="100" cy="100" r="14" stroke="#31c6ff" stroke-dasharray="55 90"/></g><rect x="143" y="84" width="7" height="18" rx="3" fill="${L}"/><rect x="56" y="52" width="88" height="96" rx="26" fill="${W}" opacity=".3"/>`,
spk:`<rect x="38" y="62" width="124" height="82" rx="40" fill="${P}"/><g fill="${shade(c,-.5)}" opacity=".55">${[0,1,2,3,4].map(r=>[...Array(14)].map((_,k)=>`<circle cx="${52+k*7.4}" cy="${80+r*11}" r="1.9"/>`).join('')).join('')}</g><rect x="38" y="62" width="124" height="82" rx="40" fill="${W}" opacity=".3"/><rect x="82" y="124" width="36" height="8" rx="4" fill="${L}" opacity=".8"/><path d="M70 62q30-30 60 0" fill="none" stroke="${D}" stroke-width="4"/>`,
hub:`<path d="M46 150a54 54 0 0 1 108 0z" fill="${P}"/><path d="M46 150a54 54 0 0 1 108 0z" fill="${W}" opacity=".4"/><ellipse cx="100" cy="104" rx="26" ry="6" fill="#0b1020"/><ellipse cx="100" cy="104" rx="26" ry="6" fill="none" stroke="#5fb4ff" stroke-width="2.5"/><ellipse cx="100" cy="104" rx="26" ry="6" fill="none" stroke="#5fb4ff" stroke-width="7" opacity=".25"/><rect x="46" y="150" width="108" height="6" rx="3" fill="${D}"/>`,
kb:`<g transform="skewX(-8) translate(18 0)"><rect x="18" y="68" width="164" height="76" rx="9" fill="${D}"/><rect x="18" y="68" width="164" height="76" rx="9" fill="none" stroke="${L}" stroke-opacity=".6"/>${[0,1,2,3,4].map(r=>[...Array(13)].map((_,k)=>r==4&&k>2&&k<10?'':`<rect x="${24+k*12.2}" y="${73+r*13.6}" width="${r==4&&k==2?7*12.2-2:10.4}" height="11.6" rx="2.4" fill="${(r==0&&k==0)||(r==2&&k==12)?'#7c5cff':'#eef1f8'}"/>`).join('')).join('')}</g>`,
mouse:`<path d="M100 30c32 0 46 30 46 64 0 42-18 80-46 80S54 136 54 94c0-34 14-64 46-64z" fill="${P}"/><path d="M100 30c32 0 46 30 46 64 0 42-18 80-46 80S54 136 54 94c0-34 14-64 46-64z" fill="${W}" opacity=".35"/><path d="M100 32v56M56 88q44 8 88 0" stroke="${D}" stroke-width="1.5" fill="none"/><rect x="94.5" y="46" width="11" height="24" rx="5.5" fill="${D}"/><rect x="96.5" y="48" width="3" height="10" rx="1.5" fill="#7c5cff"/><rect x="50" y="96" width="9" height="22" rx="4" fill="${D}"/>`,
cam:`<path d="M40 70a10 10 0 0 1 10-10h100a10 10 0 0 1 10 10v66a10 10 0 0 1-10 10H50a10 10 0 0 1-10-10z" fill="${P}"/><rect x="40" y="60" width="120" height="86" rx="10" fill="${W}" opacity=".25"/><rect x="62" y="48" width="30" height="14" rx="4" fill="${D}"/><circle cx="140" cy="76" r="4" fill="#ff3b3b"/><circle cx="100" cy="104" r="34" fill="${D}"/><circle cx="100" cy="104" r="29" fill="#0a0d18" stroke="${L}" stroke-opacity=".5"/><circle cx="100" cy="104" r="20" fill="#14214f"/><circle cx="100" cy="104" r="12" fill="#05070f"/><ellipse cx="92" cy="96" rx="7" ry="4" fill="#fff" opacity=".4" transform="rotate(-30 92 96)"/>`};
return `<svg viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg" role="img" aria-hidden="true">${defs}${n?'':`<rect width="200" height="200" fill="url(#${i}g)"/><rect width="200" height="200" fill="url(#${i}h)"/>`}<ellipse cx="100" cy="168" rx="58" ry="7" fill="#0b1020" opacity=".35" filter="url(#${i}f)"/>${B[t]||B.cam}</svg>`}
let U=0;const A=p=>`<img src="/assets/images/p${p.id}.svg" alt="${p.brand} ${p.name}" width="400" height="400" loading="lazy" decoding="async" onerror="this.outerHTML=art('${p.type}','${p.color}',${++U})">`;
/* ---------- state ---------- */
const state={products:R,cart:ar('nova_cart',[]).filter(i=>i&&R[i.id]&&i.q>0),wishlist:ar('nova_wl',[]).filter(i=>R[i]),searchQuery:'',filters:{cat:'',brands:[],max:150000,rating:0,stock:false},sort:'featured',route:'/',theme:ld('nova_theme','light'),recent:ar('nova_recent',[])};
const app=$('#app');
/* ---------- helpers ---------- */
const stars=r=>'★'.repeat(Math.round(r))+'☆'.repeat(5-Math.round(r));
function toast(m){const t=document.createElement('div');t.className='to';t.textContent=m;$('#ts').appendChild(t);setTimeout(()=>{t.classList.add('x');setTimeout(()=>t.remove(),300)},2200)}
function card(p){const w=state.wishlist.includes(p.id);return `<article class="card"><div class="im"><a href="/product/${p.id}" data-link aria-label="${p.name}">${A(p)}</a><span class="bd">${p.disc}% OFF</span><button class="wl ${w?'on':''}" data-act="wl" data-id="${p.id}" aria-label="Wishlist" aria-pressed="${w}">${w?'♥':'♡'}</button><div class="qa"><button data-act="qv" data-id="${p.id}">Quick View</button></div></div><div class="bi"><small>${p.brand}</small><h3>${p.name}</h3><div class="rt"><i>${stars(p.rating)}</i> ${p.rating} (${p.rev.toLocaleString('en-IN')})</div><div class="pr"><b>${fmt(p.price)}</b><s>${fmt(p.orig)}</s><em>${p.disc}% OFF</em></div><button class="add" data-act="add" data-id="${p.id}" ${p.stock?'':'disabled'}>${p.stock?'Add to cart':'Out of stock'}</button></div></article>`}
const save=()=>{sv('nova_cart',state.cart);sv('nova_wl',state.wishlist)};
function badges(){const n=state.cart.reduce((a,i)=>a+i.q,0);const c=$('#cn'),w=$('#wb');c.textContent=n;c.hidden=!n;w.textContent=state.wishlist.length;w.hidden=!state.wishlist.length;c.classList.remove('pop');void c.offsetWidth;c.classList.add('pop')}
function addCart(id,q=1){const p=R[id];if(!p.stock)return;const i=state.cart.find(x=>x.id==id);i?i.q=Math.min(10,i.q+q):state.cart.push({id,q});save();badges();renderCart();toast('✓ Added to cart')}
function toggleWl(id){const i=state.wishlist.indexOf(id);i<0?(state.wishlist.push(id),toast('♥ Added to wishlist')):(state.wishlist.splice(i,1),toast('Removed from wishlist'));save();badges();document.querySelectorAll(`.wl[data-id="${id}"]`).forEach(b=>{const on=state.wishlist.includes(id);b.classList.toggle('on',on);b.textContent=on?'♥':'♡';b.setAttribute('aria-pressed',on)});if(state.route=='/wishlist')go('/wishlist',1)}
function totals(){let sub=0,sav=0;state.cart.forEach(i=>{const p=R[i.id];sub+=p.orig*i.q;sav+=(p.orig-p.price)*i.q});const ship=sub-sav>5000||!sub?0:199;return{sub,sav,ship,tot:sub-sav+ship}}
const sum=t=>`<div class="ln"><span>Subtotal</span><span>${fmt(t.sub)}</span></div><div class="ln"><span>Discount</span><span style="color:#12a150">- ${fmt(t.sav)}</span></div><div class="ln"><span>Shipping</span><span>${t.ship?fmt(t.ship):'FREE'}</span></div><div class="ln tt"><span>Total</span><span>${fmt(t.tot)}</span></div>`;
function renderCart(){const n=state.cart.length,t=totals();$('#dr').innerHTML=`<div class="dh"><h3>Your Cart (${state.cart.reduce((a,i)=>a+i.q,0)})</h3><button class="ib" data-act="close" aria-label="Close cart">✕</button></div><div class="db">${n?state.cart.map(i=>{const p=R[i.id];return `<div class="ci"><div class="t">${A(p)}</div><div><b>${p.name}</b><div class="rt">${p.brand}</div><div class="qty" style="margin-top:6px"><button data-act="dq" data-id="${p.id}" aria-label="Decrease">−</button><span>${i.q}</span><button data-act="iq" data-id="${p.id}" aria-label="Increase">+</button></div></div><div style="text-align:right"><b>${fmt(p.price*i.q)}</b><br><button data-act="rm" data-id="${p.id}" style="color:#ef3b5c;font-size:13px;margin-top:8px">Remove</button></div></div>`}).join(''):`<div class="em"><div class="big">🛍</div><h2>Your cart is waiting.</h2><p>Discover something you'll love.</p><button class="btn" data-act="shop">Start Shopping</button></div>`}</div>${n?`<div class="df">${sum(t)}<button class="btn w100" data-act="chk">Proceed to Checkout →</button></div>`:''}`}
function openLayer(id){$('#ov').classList.add('o');$(id).classList.add('o')}
function closeAll(){['#dr','#md','#ov','#fl'].forEach(s=>{const e=$(s);e&&e.classList.remove('o')})}
/* ---------- views ---------- */
const catCard=(c,i)=>`<a class="cat rvl" style="transition-delay:${i*80}ms" href="/category/${c[0]}" data-link><div class="im">${art(c[2],['#7c8cff','#9aa3b5','#3a3f55','#c9ccd6','#4b5878','#6a5a8a'][i],++U)}</div><div class="t"><b>${c[0]}</b><small>${c[1]}</small> <span class="ar">→</span></div></a>`;
function home(){const dl=R.filter(p=>p.disc>=15).slice(0,4);return `<section class="hero"><div class="w hg"><div><h1>Everything you need.<br><span>One place.</span></h1><p>Discover premium tech, lifestyle and everyday essentials designed for modern living.</p><div class="hb2"><a class="btn" href="/shop" data-link>Shop Now →</a><a class="btn g" href="/#cats" data-link>Explore Collections</a></div><div class="stats"><div><b>500+</b>Premium products</div><div><b>50K+</b>Happy customers</div><div><b>4.8★</b>Average rating</div></div></div><div class="hv"><div class="a">${art('head','#1b1f2e',++U,1)}</div><div class="b">${art('phone','#8a8f9c',++U,1)}</div><div class="c">${art('laptop','#b9bcc6',++U,1)}</div></div></div></section>
<section class="sec" id="cats"><div class="w"><div class="sh2"><h2>Shop by Category</h2><a href="/shop" data-link>View all →</a></div><div class="cats">${CATS.map(catCard).join('')}</div></div></section>
<section class="w rvl"><div class="ban"><div><h2>Upgrade your setup.</h2><p>Up to 40% off selected tech. Premium audio, immersive sound.</p><a class="btn g" href="/category/Audio" data-link style="margin-top:18px">Shop Audio →</a></div><div>${art('head','#2a3050',++U,1)}</div></div></section>
<section class="sec"><div class="w"><div class="sh2"><h2>Featured Products</h2><a href="/shop" data-link>View all →</a></div><div class="grid">${R.slice(0,8).map(card).join('')}</div></div></section>
<section class="sec" id="deals" style="padding-top:0"><div class="w"><div class="sh2"><h2>Today's Deals</h2><div class="tm" id="tm" aria-label="Time left"><span>08</span>:<span>42</span>:<span>17</span></div></div><div class="grid">${dl.map(p=>card(p).replace('<div class="pr">',`<div class="pg" title="${p.sold}% claimed"><i style="width:${p.sold}%"></i></div><div class="pr">`)).join('')}</div></div></section>
<section class="w rvl"><div class="ban b2"><div><h2>Smart living starts here.</h2><p>Voice, display and home hubs that make every day easier.</p><a class="btn g" href="/category/Smart Home" data-link style="margin-top:18px">Explore →</a></div><div>${art('hub','#3b4a63',++U,1)}</div></div><div class="tr"><div><b>Free delivery</b><span>On orders over ₹5,000</span></div><div><b>7-day returns</b><span>No questions asked</span></div><div><b>1-year warranty</b><span>Official warranty</span></div><div><b>Secure payments</b><span>Encrypted checkout</span></div></div></section>`}
function list(){const f=state.filters;let r=R.filter(p=>(!f.cat||p.cat==f.cat)&&(!f.brands.length||f.brands.includes(p.brand))&&p.price<=f.max&&p.rating>=f.rating&&(!f.stock||p.stock));const s=state.sort;const S={'new':(a,b)=>b.id-a.id,'lh':(a,b)=>a.price-b.price,'hl':(a,b)=>b.price-a.price,'rt':(a,b)=>b.rating-a.rating,'ds':(a,b)=>b.disc-a.disc};if(S[s])r=[...r].sort(S[s]);return r}
function fillGrid(){const r=list(),g=$('#grid');if(!g)return;$('#cnt').textContent=`${r.length} results${state.filters.cat?` in "${state.filters.cat}"`:''}`;g.innerHTML=r.length?r.map(card).join(''):`<div class="em" style="grid-column:1/-1"><div class="big">🔍</div><h2>No products found.</h2><p>Try adjusting your filters.</p><button class="btn" data-act="reset">Clear filters</button></div>`}
function shop(cat){state.filters.cat=cat||'';const f=state.filters,brands=[...new Set(R.map(p=>p.brand))].sort();
app.innerHTML=`<div class="w"><div class="pgh"><div class="crumb">Home / Shop${cat?' / '+cat:''}</div><h1>${cat||'Shop all'}</h1></div><div class="shop"><aside class="fl" id="fl" aria-label="Filters"><h4>Category</h4>${['',...CATS.map(c=>c[0])].map(c=>`<label><input type="radio" name="cat" value="${c}" ${f.cat==c?'checked':''}>${c||'All'}</label>`).join('')}<h4>Brand</h4>${brands.map(b=>`<label><input type="checkbox" data-b="${b}" ${f.brands.includes(b)?'checked':''}>${b}</label>`).join('')}<h4>Max price: <span id="mx">${fmt(f.max)}</span></h4><input type="range" id="pr" min="1000" max="150000" step="1000" value="${f.max}" aria-label="Max price"><h4>Rating</h4>${[0,4,4.5].map(v=>`<label><input type="radio" name="rt" value="${v}" ${f.rating==v?'checked':''}>${v?v+'★ & above':'All'}</label>`).join('')}<h4>Availability</h4><label><input type="checkbox" id="st" ${f.stock?'checked':''}>In stock only</label><button class="btn w100 fb" data-act="close" style="margin-top:16px">Show results</button></aside><div><div class="tb"><button class="btn o fb" data-act="fl">Filters</button><span id="cnt" class="rt"></span><select id="so" aria-label="Sort"><option value="featured">Featured</option><option value="new">Newest</option><option value="lh">Price low → high</option><option value="hl">Price high → low</option><option value="rt">Highest rated</option><option value="ds">Biggest discount</option></select></div><div class="grid" id="grid">${'<div class="sk"></div>'.repeat(8)}</div></div></div></div>`;
$('#so').value=state.sort;const rt=state.route;setTimeout(()=>{if(state.route==rt)fillGrid(),obs()},380)}
function product(id){const p=R[id];if(!p)return nf();document.title=`${p.brand} ${p.name} — NOVA`;const V=['','scale(1.35) translateY(6%)','rotate(-14deg)','scaleX(-1) scale(.9)'];const cols=[p.color,'#c9ccd6','#4a6fd8','#e0a8b0'];
app.innerHTML=`<div class="w"><div class="crumb" style="padding-top:24px">Home / ${p.cat} / ${p.name}</div><div class="pd"><div><div class="mi" id="mi">${A(p)}</div><div class="th">${V.map((v,i)=>`<button data-act="th" data-v="${v}" class="${i?'':'on'}" aria-label="View ${i+1}">${art(p.type,p.color,++U).replace('<svg','<svg style="transform:'+v+'"')}</button>`).join('')}</div></div>
<div><small class="rt">${p.brand}</small><h1>${p.name}</h1><div class="rt"><i>${stars(p.rating)}</i> ${p.rating} (${p.rev.toLocaleString('en-IN')} reviews) · <span style="color:${p.stock?'#12a150':'#ef3b5c'}">${p.stock?'● In stock':'● Out of stock'}</span></div><div class="pr"><b>${fmt(p.price)}</b><s>${fmt(p.orig)}</s><em>${p.disc}% OFF</em></div><p style="color:var(--mu)">Premium ${p.cat.toLowerCase()} engineered for everyday performance — refined design, class-leading quality and all-day reliability.</p><b>Color</b><div class="sw">${cols.map((c,i)=>`<button style="background:${c}" class="${i?'':'on'}" data-act="sw" aria-label="Color ${i+1}"></button>`).join('')}</div><div class="qty" id="pq"><button data-act="pq-" aria-label="Decrease">−</button><span id="pqv">1</span><button data-act="pq+" aria-label="Increase">+</button></div>
<div class="row"><button class="btn add" style="height:50px" data-act="padd" data-id="${id}" ${p.stock?'':'disabled'}>Add to Cart</button><button class="btn" style="background:var(--tx);color:var(--bg)" data-act="buy" data-id="${id}" ${p.stock?'':'disabled'}>Buy Now</button><button class="btn o wl2 wl ${state.wishlist.includes(id)?'on':''}" style="position:static;width:50px;flex:none;border-radius:12px" data-act="wl" data-id="${id}" aria-label="Wishlist">${state.wishlist.includes(id)?'♥':'♡'}</button></div>
<div class="tr" style="grid-template-columns:1fr 1fr 1fr;margin:0"><div><b>Free delivery</b><span>3–5 days</span></div><div><b>7 days return</b><span>Easy</span></div><div><b>1 yr warranty</b><span>Official</span></div></div></div></div>
<div class="tabs" role="tablist">${['Overview','Specifications','Reviews','FAQ'].map((t,i)=>`<button role="tab" data-act="tab" data-i="${i}" class="${i?'':'on'}">${t}</button>`).join('')}</div><div class="tp" id="tp"></div>
<div class="sec"><div class="sh2"><h2>You may also like</h2></div><div class="grid">${R.filter(x=>x.cat==p.cat&&x.id!=id).slice(0,4).map(card).join('')}</div></div></div>`;tab(0,p)}
function tab(i,p=R[+location.hash||window.__pid]){const P=window.__p;p=P||p;const T=[`<p>The ${p.brand} ${p.name} blends refined industrial design with outstanding performance. Built with premium materials and tuned for real-world use, it's an easy upgrade for your everyday setup.</p><ul><li>Flagship-grade performance</li><li>All-day battery life</li><li>Premium build quality</li><li>Official brand warranty</li></ul>`,
[['Brand',p.brand],['Category',p.cat],['Warranty','1 year manufacturer'],['In the box','Product, accessories, documentation'],['Delivery','Free over ₹5,000']].map(r=>`<div class="spec"><span>${r[0]}</span><b>${r[1]}</b></div>`).join(''),
[['Aarav M.','Excellent quality and fast delivery.'],['Priya S.','Exactly as described. Packaging was premium.'],['Rohan K.','Worth every rupee — easily the best in this range.']].map(r=>`<div class="rv"><i style="color:#f5a623">★★★★★</i> <b>${r[0]}</b> <small>· Verified purchase</small><p style="margin:6px 0 0">${r[1]}</p></div>`).join(''),
[['Is it genuine?','Yes — 100% authentic with official brand warranty.'],['How fast is delivery?','Most orders arrive within 3–5 business days.'],['Can I return it?','Yes, within 7 days of delivery.']].map(r=>`<details><summary>${r[0]}</summary><p>${r[1]}</p></details>`).join('')];
$('#tp').innerHTML=`<div class="tp">${T[i]}</div>`;document.querySelectorAll('[data-act=tab]').forEach(b=>b.classList.toggle('on',b.dataset.i==i))}
function wish(){app.innerHTML=`<div class="w"><div class="pgh"><h1>My Wishlist (${state.wishlist.length})</h1><p class="crumb">Your saved products</p></div>${state.wishlist.length?`<div class="grid" style="padding:20px 0 60px">${state.wishlist.map(i=>card(R[i])).join('')}</div>`:`<div class="em"><div class="big">♡</div><h2>Save what you love.</h2><p>Tap the heart on any product to keep it here.</p><button class="btn" data-act="shop">Start Shopping</button></div>`}</div>`}
const nf=()=>app.innerHTML=`<div class="em"><h2>Page not found</h2><p>That page doesn't exist.</p><a class="btn" href="/" data-link>Go home</a></div>`;
let step=0;const ci={};
function checkout(){if(!state.cart.length){return app.innerHTML=`<div class="em"><div class="big">🛍</div><h2>Your cart is waiting.</h2><p>Discover something you'll love.</p><button class="btn" data-act="shop">Start Shopping</button></div>`}
const t=totals(),L=['Information','Shipping','Payment','Review'];
const F=[`<h3>Contact information</h3><label for="f_n">Full name</label><input class="in" id="f_n" autocomplete="name" value="${ci.n||''}"><div class="g2"><div><label for="f_e">Email</label><input class="in" id="f_e" type="email" value="${ci.e||''}"></div><div><label for="f_p">Phone</label><input class="in" id="f_p" type="tel" value="${ci.p||''}"></div></div>`,
`<h3>Shipping address</h3><label for="f_a">Address</label><input class="in" id="f_a" value="${ci.a||''}"><div class="g2"><div><label for="f_c">City</label><input class="in" id="f_c" value="${ci.c||''}"></div><div><label for="f_s">State</label><input class="in" id="f_s" value="${ci.s||'Tamil Nadu'}"></div></div><label for="f_z">Postal code</label><input class="in" id="f_z" inputmode="numeric" value="${ci.z||''}">`,
`<h3>Payment method</h3>${['Credit / Debit Card','UPI (GPay, PhonePe, Paytm)','Cash on Delivery'].map((m,i)=>`<label class="pm"><input type="radio" name="pay" value="${m}" ${(ci.pay||'Credit / Debit Card')==m?'checked':''}>${m}</label>`).join('')}`,
`<h3>Review your order</h3><p>${ci.n} · ${ci.e}<br>${ci.a}, ${ci.c}, ${ci.s} ${ci.z}<br>Payment: ${ci.pay}</p>`+state.cart.map(i=>`<div class="ln"><span>${R[i.id].name} × ${i.q}</span><span>${fmt(R[i.id].price*i.q)}</span></div>`).join('')];
app.innerHTML=`<div class="w"><div class="steps">${L.map((l,i)=>`<div class="${i<=step?'d':''}"><i></i>${i+1} ${l}</div>`).join('')}</div><div class="co"><div class="bx">${F[step]}<div class="row">${step?'<button class="btn o" data-act="back" style="flex:none">Back</button>':''}<button class="btn" data-act="next">${step==3?'Place Order':'Continue'}</button></div></div><div class="bx" style="position:sticky;top:90px"><h3>Order summary</h3>${state.cart.map(i=>`<div class="ci" style="grid-template-columns:48px 1fr auto"><div class="t" style="width:48px;height:48px">${A(R[i.id])}</div><span>${R[i.id].name}<br><small class="rt">Qty ${i.q}</small></span><b>${fmt(R[i.id].price*i.q)}</b></div>`).join('')}${sum(t)}</div></div></div>`}
function next(){const g=id=>($('#'+id)||{}).value||'';if(step==0){Object.assign(ci,{n:g('f_n').trim(),e:g('f_e').trim(),p:g('f_p').trim()});if(!ci.n||!/^\S+@\S+\.\S+$/.test(ci.e)||ci.p.replace(/\D/g,'').length<10)return toast('Please enter valid contact details')}
if(step==1){Object.assign(ci,{a:g('f_a').trim(),c:g('f_c').trim(),s:g('f_s').trim(),z:g('f_z').trim()});if(!ci.a||!ci.c||!/^\d{6}$/.test(ci.z))return toast('Please complete your address (6-digit postal code)')}
if(step==2){const r=document.querySelector('[name=pay]:checked');ci.pay=r?r.value:'Credit / Debit Card'}
if(step==3){const t=totals();window.__o={no:'NV'+Math.floor(100000+Math.random()*899999),items:state.cart.map(i=>({...i})),tot:t.tot};state.cart=[];save();badges();renderCart();step=0;toast('✓ Order placed');return go('/order-success')}
step++;checkout();window.scrollTo(0,0)}
function success(){const o=window.__o;if(!o)return go('/',1);const d=new Date(Date.now()+4*864e5).toLocaleDateString('en-IN',{day:'numeric',month:'short'});
app.innerHTML=`<div class="w ok2"><svg class="ck" viewBox="0 0 100 100"><circle cx="50" cy="50" r="46"/><path d="M30 52l14 14 27-30"/></svg><h1>Order Confirmed!</h1><p class="rt">Thank you for your purchase. Estimated delivery by ${d}.</p><div class="bx" style="max-width:480px;margin:24px auto;text-align:left"><b>Order #${o.no}</b>${o.items.map(i=>`<div class="ln"><span>${R[i.id].name} × ${i.q}</span></div>`).join('')}<div class="ln tt" style="margin-bottom:0"><span>Total paid</span><span>${fmt(o.tot)}</span></div></div><div class="row" style="justify-content:center"><a class="btn" href="/shop" data-link style="flex:none">Continue Shopping</a><button class="btn o" data-act="nf" style="flex:none">View Orders</button></div></div>`;
for(let i=0;i<40;i++){const c=document.createElement('i');c.className='cf';c.style.cssText=`left:${Math.random()*100}vw;background:${['#2f6bff','#7c5cff','#12a150','#f5a623'][i%4]};animation-delay:${Math.random()*.8}s`;document.body.appendChild(c);setTimeout(()=>c.remove(),3500)}}
/* ---------- router ---------- */
function go(path,replace){try{replace?history.replaceState({},'',path):history.pushState({},'',path)}catch(e){}render(path.split('#')[0])}
function render(path){closeAll();state.route=path;document.title='NOVA — Everything you need. One place.';app.classList.remove('pgv');void app.offsetWidth;
const seg=decodeURIComponent(path).split('/').filter(Boolean);
if(!seg.length)home();else if(seg[0]=='shop')shop();else if(seg[0]=='category')shop(seg[1]);else if(seg[0]=='product'){window.__p=R[+seg[1]];product(+seg[1])}else if(seg[0]=='wishlist')wish();else if(seg[0]=='checkout')checkout();else if(seg[0]=='order-success')success();else if(seg[0]=='cart'){home();openCart()}else nf();
app.classList.add('pgv');document.querySelectorAll('#lk a').forEach(a=>a.classList.toggle('on',a.getAttribute('href')==('/'+(seg[0]||''))||(!seg.length&&a.getAttribute('href')=='/')));window.scrollTo(0,0);obs();$('#mn').classList.remove('o')}
function pathNow(){let p='/';try{p=location.pathname}catch(e){}return /^\/(shop|category|product|wishlist|checkout|order-success|cart)/.test(p)?p:'/'}
function openCart(){renderCart();openLayer('#dr')}
function obs(){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.rvl:not(.in)').forEach(e=>io.observe(e))}
/* ---------- events ---------- */
document.addEventListener('click',e=>{const a=e.target.closest('a[data-link]');if(a){e.preventDefault();const h=a.getAttribute('href');go(h);if(h.includes('#')){const id=h.split('#')[1];setTimeout(()=>{const el=document.getElementById(id);el&&el.scrollIntoView({behavior:'smooth'})},120)}$('#dd').classList.remove('o');return}
if(e.target.id=='ov')return closeAll();
const b=e.target.closest('[data-act]');if(!b)return;const act=b.dataset.act,id=+b.dataset.id;
const A2={wl:()=>toggleWl(id),add:()=>{addCart(id);b.classList.add('ok');b.textContent='✓ Added';setTimeout(()=>{b.classList.remove('ok');b.textContent='Add to cart'},1400)},
qv:()=>{const p=R[id];window.__q=1;$('#md').innerHTML=`<button class="cl" data-act="close" aria-label="Close">✕</button><div class="pd"><div class="mi" style="cursor:default">${A(p)}</div><div><small class="rt">${p.brand}</small><h1>${p.name}</h1><div class="rt"><i>${stars(p.rating)}</i> ${p.rating} (${p.rev.toLocaleString('en-IN')})</div><div class="pr"><b>${fmt(p.price)}</b><s>${fmt(p.orig)}</s><em>${p.disc}% OFF</em></div><p style="color:var(--mu)">Premium ${p.cat.toLowerCase()} with flagship build quality and an official brand warranty.</p><div class="qty"><button data-act="mq-">−</button><span id="mqv">1</span><button data-act="mq+">+</button></div><div class="row"><button class="btn" data-act="madd" data-id="${id}">Add to Cart</button></div><a class="rt" href="/product/${id}" data-link>View full details →</a></div></div>`;openLayer('#md');$('#md .cl').focus()},
'mq-':()=>{window.__q=Math.max(1,window.__q-1);$('#mqv').textContent=window.__q},'mq+':()=>{window.__q=Math.min(10,window.__q+1);$('#mqv').textContent=window.__q},madd:()=>{addCart(id,window.__q);closeAll()},
close:closeAll,fl:()=>{$('#ov').classList.add('o');$('#fl').classList.add('o')},iq:()=>{state.cart.find(i=>i.id==id).q++;save();badges();renderCart()},dq:()=>{const i=state.cart.find(i=>i.id==id);if(--i.q<1)state.cart=state.cart.filter(x=>x!=i);save();badges();renderCart();toast('✓ Cart updated')},rm:()=>{state.cart=state.cart.filter(i=>i.id!=id);save();badges();renderCart();toast('✓ Cart updated')},
chk:()=>{closeAll();go('/checkout')},shop:()=>{closeAll();go('/shop')},reset:()=>{state.filters={cat:'',brands:[],max:150000,rating:0,stock:false};go('/shop',1)},nf:()=>toast('This page is coming soon'),acc:()=>toast('Sign-in is coming soon'),
th:()=>{document.querySelectorAll('.th button').forEach(x=>x.classList.remove('on'));b.classList.add('on');const m=$('#mi svg,#mi img');m.style.opacity=0;setTimeout(()=>{m.style.transform=b.dataset.v;m.style.opacity=1},200)},
sw:()=>{document.querySelectorAll('.sw button').forEach(x=>x.classList.remove('on'));b.classList.add('on');$('#mi svg,#mi img').style.filter=`hue-rotate(${Math.random()*40-20}deg)`},
'pq-':()=>{$('#pqv').textContent=Math.max(1,+$('#pqv').textContent-1)},'pq+':()=>{$('#pqv').textContent=Math.min(10,+$('#pqv').textContent+1)},
padd:()=>{addCart(id,+$('#pqv').textContent);b.textContent='✓ Added';setTimeout(()=>b.textContent='Add to Cart',1400)},buy:()=>{addCart(id,+$('#pqv').textContent);closeAll();go('/checkout')},tab:()=>tab(+b.dataset.i,window.__p),next,back:()=>{step--;checkout()}};
if(A2[act]){e.preventDefault();A2[act]()}});
document.addEventListener('change',e=>{const t=e.target,f=state.filters;if(t.name=='cat'){f.cat=t.value}else if(t.dataset.b){f.brands=[...document.querySelectorAll('[data-b]:checked')].map(x=>x.dataset.b)}else if(t.name=='rt'){f.rating=+t.value}else if(t.id=='st'){f.stock=t.checked}else if(t.id=='so'){state.sort=t.value}else return;fillGrid();obs()});
document.addEventListener('input',e=>{if(e.target.id=='pr'){state.filters.max=+e.target.value;$('#mx').textContent=fmt(state.filters.max);fillGrid()}});
document.addEventListener('keydown',e=>{if(e.key=='Escape'){closeAll();$('#dd').classList.remove('o')}});
window.addEventListener('popstate',()=>render(pathNow()));
window.addEventListener('scroll',()=>$('#nb').classList.toggle('sc',scrollY>20),{passive:true});
$('#cb').onclick=openCart;$('#hb').onclick=()=>$('#mn').classList.toggle('o');$('#sb').onclick=()=>{$('#sr').classList.toggle('open');$('#q').focus()};
function setTheme(t){state.theme=t;document.documentElement.dataset.t=t;sv('nova_theme',t)}
$('#th').onclick=()=>setTheme(state.theme=='dark'?'light':'dark');setTheme(state.theme=='dark'?'dark':'light');
/* search */
const dd=$('#dd');$('#q').addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase();state.searchQuery=q;if(!q){if(state.recent.length){dd.innerHTML='<p><small>Recent searches</small></p>'+state.recent.map(r=>`<p><span>${r}</span></p>`).join('');dd.classList.add('o')}else dd.classList.remove('o');return}
const r=R.filter(p=>(p.name+p.brand+p.cat+p.type).toLowerCase().includes(q)).slice(0,6);dd.innerHTML=r.length?r.map(p=>`<a href="/product/${p.id}" data-link role="option"><div class="t">${A(p)}</div><span><b>${p.name}</b><small>${p.brand} · ${fmt(p.price)}</small></span></a>`).join(''):'<p>No products found.</p>';dd.classList.add('o')});
$('#q').addEventListener('keydown',e=>{if(e.key=='Enter'&&state.searchQuery){state.recent=[state.searchQuery,...state.recent.filter(x=>x!=state.searchQuery)].slice(0,4);sv('nova_recent',state.recent);const r=R.find(p=>(p.name+p.brand).toLowerCase().includes(state.searchQuery));r?go('/product/'+r.id):toast('No products found.');dd.classList.remove('o');e.target.value=''}});
document.addEventListener('click',e=>{if(!e.target.closest('#sr'))dd.classList.remove('o')});
/* countdown */
let end=Date.now()+(8*3600+42*60+17)*1000;setInterval(()=>{const t=$('#tm');if(!t)return;let s=Math.max(0,Math.floor((end-Date.now())/1000));t.innerHTML=[s/3600|0,(s%3600)/60|0,s%60].map(n=>`<span>${String(n).padStart(2,'0')}</span>`).join(':')},1000);
badges();renderCart();render(pathNow());
